version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clusterdb
    ports:
      - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
      - sems-net
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - sems-net
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
        - sems-net
  
  
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - datain
    networks:
      - sems-net

  datain:
    build:
      context: .
      dockerfile: DataIngestionService/Dockerfile
    ports:
      - "5001:80"
    networks:
        - sems-net

  processing:
    build:
      context: .
      dockerfile: ProcessingService/Dockerfile
    depends_on:
      - postgres
    networks:
      - sems-net

  metrics:
    build:
      context: .
      dockerfile: MetricsService/Dockerfile
    ports:
      - "5002:80"
    networks:
      - sems-net

  
  simulator:
    build:
      context: .
      dockerfile: DeviceSimulator/Dockerfile
    networks:
      - sems-net
    depends_on:
        - datain

networks:
  sems-net:

volumes:
  pgdata:
  grafana-storage:

