version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: clusterdb
    ports:
      - "5432:5432"
    volumes:
        - pgdata:/var/lib/postgresql/data
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
        
  apigateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - processing

  datain:
    build:
      context: .
      dockerfile: DataIngestionService/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - processing
  
  processing:
    build:
      context: .
      dockerfile: ProcessingService/Dockerfile
    depends_on:
      - postgres

  metrics:
    build:
      context: .
      dockerfile: MetricsService/Dockerfile
    ports:
      - "5002:80"
  
  simulator:
    build:
      context: .
      dockerfile: DeviceSimulator/Dockerfile

volumes:
  pgdata:
  grafana-storage:

