global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'metrics-service'
    static_configs:
      - targets: ['metrics:80']

  - job_name: 'apigateway'
    static_configs:
      - targets: ['apigateway:80']

  - job_name: 'processing'
    static_configs:
      - targets: ['processing:80']
